name: 🐛 Bug Report
description: Submit discovered bugs
title: "[🐛 Bug Report]: "
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Please ensure you have read [bug report](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Afeature+request+type%3Abug), and provide all the information required by this template, otherwise the issue will be closed immediately.

  - type: textarea
    id: environment-info
    attributes:
      label: Environment
      description: Please provide your OS, OS Language, Display Card, CPU. You can find the required information on [Mac](https://support.apple.com/en-my/guide/system-information/syspr35536/mac) or on [Windows](https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85).
      placeholder: 'OS: Windows 11 Pro, 
      OS Language: English, 
      Display Card: NVIDIA GeForce RTX 3070 Ti Laptop GPU, 
      CPU: 12th Gen Intel(R) i9-12900H'
    validations:
      required: true

  - type: textarea
    id: what-expected
    attributes:
      label: What is expected?
    validations:
      required: true

  - type: textarea
    id: actual-happened
    attributes:
      label: What is actually happening?
    validations:
      required: true

  - type: textarea
    id: reproducible-bugs
    attributes:
      label: Reproducible Bugs
      description: Kindly confirm if the issue is reproducible and provide the step-by-step process to reproduce it, if applicable. 
    validations:
      required: false

  - type: input
    id: support-link
    attributes:
      label: Related link
      description: Link to related bug report
      placeholder: https://youtu.be/...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Additional info
      description: logs, errors, etc.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: This is not a duplicated issue
      options:
        - label: I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Afeature+request+type%3Abug) to ensure this bug has not already been reported
          required: true

  - type: checkboxes
    id: no-personal-information-provided-terms
    attributes:
      label: No personal information provided
      options: 
        - label: I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.
          required: true

  - type: checkboxes
    id: open-ticket-if-needed-terms
    attributes:
      label: Open ticket if needed
      options: 
        - label: In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.
          required: true
