name: 🤔 Questions and Help
description: You need help with the battle demo.
title: "[🤔 Questions and Help]: "
labels: ["questions and help"]

body:
  - type: textarea
    id: questions-and-help
    attributes:
      label: Questions and Help
      placeholder: If you have any questions or require assistance.
    validations:
      required: true

  - type: checkboxes
    id: no-personal-information-provided-terms
    attributes:
      label: No personal information provided
      options:
        - label: I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.
          required: true

  - type: checkboxes
    id: open-ticket-if-needed-terms
    attributes:
      label: Open ticket if needed
      options:
        - label: In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeironnft) channel and reference the specific issue on Github.
          required: true
