name: Add Label to New Issues
on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  add_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Label Output
        id: label
        run: |
          if [[ "${{ github.event.issue.labels }}" != *"production"* && "${{ github.event.issue.labels }}" != *"beta"* ]]; then
            if [[ "${{ github.event.issue.body }}" == *"Production"* ]]; then
              echo "label=production" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.issue.body }}" == *"Beta Test"* ]]; then
              echo "label=beta" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Apply Label
        id: apply-label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["${{ steps.label.outputs.label }}"]
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}