name: Add Labels to Issues
on:
  issues:
    types:
      - opened

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add labels based on demo environment
        uses: actions/github-script@v4
        with:
          script: |
            const issue = context.payload.issue;
            const issueBodyLines = issue.body.split('\n');
            const fieldLine = issueBodyLines.find(line => line.includes('Demo Environment'));
            const environment = fieldLine.split(':')[1].trim();
            const labelsToAdd = [];

            if (environment === 'Production') {
              labelsToAdd.push('production');
            } else if (environment === 'Beta Test') {
              labelsToAdd.push('beta');
            }

            if (labelsToAdd.length > 0) {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labelsToAdd
              });
            }